[workspace]
resolver = "2"
members = [
    "projecteuler",
    "pe_0001",
    "pe_0005",
    "pe_0008",
    "pe_0011",
    "pe_0013",
    "pe_0023",
    "pe_0040",
    "pe_0048",
]

[workspace.dependencies]
itertools = "0.11"
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"] }
