[package]
name = "projecteuler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

pe_0001 = { path = "../pe_0001"}
pe_0005 = { path = "../pe_0005"}
